site_name: Dial Documentation
site_author: ItsAleph
site_dir: build
site_url: https://itsaleph.github.io/dial-docs
site_description: Unified documentation for public and private Discord's APIs.

repo_name: GitHub
repo_url: https://github.com/ItsAleph/dial-docs

copyright: Copyright 2023-present ItsAleph

docs_dir: src

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: rose-pine
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: rose-pine-dawn
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Introduction': 'index.md'
  - 'Unofficial APIs':
    - 'Overview': 'unofficial/index.md'
    - 'Attachments': 'unofficial/attachments.md'
    - 'Client-side Interactions': 'unofficial/client_side_interactions.md'

extra_css:
  - assets/stylesheets/extra.css
