[project]
name = ""
version = ""
description = ""
authors = [
    {name = "ItsAleph", email = "igorekkrupskij@gmail.com"},
]
dependencies = [
    "mkdocs-material>=9.1.5",
]
requires-python = ">=3.10"
license = {text = "MIT"}


[tool.pdm]
