name: ci

on:
  push:
    branches:
      - master 

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.x
          cache: true
          prerelease: true
      - run: pdm install
      - run: eval $(pdm venv activate in-project)
      - run: mkdocs gh-deploy --force
